### ISSUE TITLE
Signup on site

### ISSUE THREAD

**Issue by vipulnsward** [vipulnsward/selenium-tests#1]
Add test to signup on http://automationpractice.com/index.php

**Comment by supriyaagarwal** [comment]
![1538837022340](https://user-images.githubusercontent.com/39996151/46572504-894acb80-c9a4-11e8-9fce-0eb45ae92210.png)
![1538837027557](https://user-images.githubusercontent.com/39996151/46572505-894acb80-c9a4-11e8-96ef-444078f78a02.png)
