### ISSUE TITLE
Add test for login with existing user

### ISSUE THREAD

**Issue by vipulnsward** [vipulnsward/selenium-tests#2]
http://automationpractice.com/index.php

**Comment by supriyaagarwal** [comment]
![1538826502446](https://user-images.githubusercontent.com/39996151/46571096-91970c80-c98c-11e8-9f7f-6cd5fb93696b.png)
![1538826508559](https://user-images.githubusercontent.com/39996151/46571097-91970c80-c98c-11e8-929d-d34e8f491b0c.png)
