### ISSUE TITLE
Test for add to cart

### ISSUE THREAD

**Issue by vipulnsward** [vipulnsward/selenium-tests#3]
- [x] Add to cart in logged in mode
- [x] Add to cart in logged out mode

**Comment by supriyaagarwal** [comment]
![1538816145090](https://user-images.githubusercontent.com/39996151/46569661-bf248b80-c975-11e8-92d7-3da1705e9efd.png)
![1538816851351](https://user-images.githubusercontent.com/39996151/46569662-bfbd2200-c975-11e8-9e08-91e1ba52e035.png)
