### ISSUE TITLE
Product page verification

### ISSUE THREAD

**Issue by vipulnsward** [vipulnsward/selenium-tests#4]
- More information page
- Quick view page

- Share links
- Add to cart with various quantity, size, swatch

**Comment by supriyaagarwal** [comment]
![1538907368826](https://user-images.githubusercontent.com/39996151/46580775-26f7d680-ca49-11e8-8d94-162ae41f2560.png)
![1538907705735](https://user-images.githubusercontent.com/39996151/46580776-26f7d680-ca49-11e8-9b85-24498fbb9f03.png)
