### ISSUE TITLE
Add test for simple search

### ISSUE THREAD

**Issue by vipulnsward** [vipulnsward/selenium-tests#7]
- Search 
- Sort
- View types

**Comment by supriyaagarwal** [comment]
![1538818403767](https://user-images.githubusercontent.com/39996151/46570811-dc625580-c987-11e8-813d-3eb22c9bc21a.png)

**Comment by supriyaagarwal** [comment]
![1538825086090](https://user-images.githubusercontent.com/39996151/46570854-a2de1a00-c988-11e8-8837-76d779060e08.png)
![1538825091224](https://user-images.githubusercontent.com/39996151/46570855-a376b080-c988-11e8-9bba-80e73913dd24.png)
![1538825094609](https://user-images.githubusercontent.com/39996151/46570856-a376b080-c988-11e8-95bf-f83534e9b8fd.png)
